### ISSUE TITLE
Not getting data in report

### ISSUE THREAD

**Issue by QA-Rahul** [simple-elf/allure-report-action#10]
Somehow my report is generating empty. 

![image](https://user-images.githubusercontent.com/18675695/123937124-7a59a200-d9b3-11eb-8b81-5f323f547fef.png)

Is there anything I am missing.  I can see all the files are getting generated but those are also empty. 

I am using Java, Selenium and Maven. I have not added anything in as code in project for allure, I directly add what is required in github actions .yml file.

Please let me know if it need any other specific configuration.

**Comment by saikirangit** [comment]
Were you able to resolve this?

**Comment by emarty-maze** [comment]
@QA-Rahul @saikirangit I fixed the issue by copying the action from the workflow in the repo:

https://github.com/simple-elf/allure-report-action/blob/master/.github/workflows/allure-report.yml

```
- name: Allure Report action from marketplace
  uses: simple-elf/allure-report-action@master
  if: always()
  #id: allure-report
  with:
    allure_results: allure-results
    #gh_pages: gh-pages
    #allure_report: allure-report
    allure_history: allure-history
    keep_reports: 20
```
