### ISSUE TITLE
Unable to push the gh-pages directory

### ISSUE THREAD

**Issue by amrsa1** [simple-elf/allure-report-action#17]
I'm facing the following issue, on self-hosted runner, run is failing on the deploy allure report step

```
  - name: Retrive allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with: 
          ref: gh-pages
          path: gh-pages  

      - name: Gnerate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
```

error: failed to push some refs to '***github.com/user/test-automation-web.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
