### ISSUE TITLE
History not kept

### ISSUE THREAD

**Issue by dmarkey** [simple-elf/allure-report-action#41]
Hey there,

For some reason the history is not kept for me, only the latest.

```
- name: Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results:  ui_regression/results/
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20
  ```
        
 Do I have something configured wrong?
