### ISSUE TITLE
 Container action is only supported on Linux

### ISSUE THREAD

**Issue by rahulshrivastava-eaton** [simple-elf/allure-report-action#44]
It is not working with Windows self hosted runners, We are getting the error 
"Container action is only supported on Linux"

**Comment by mgrybyk** [comment]
Hello,
this is a limitation of the Dockerfile based Github action runner, see https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions

It's possible to workaround the issue by running Javascript based action. However, allure is Java based so it's required to install Java in advance.
Please let me know @rahulshrivastava-eaton if you are interested.

**Comment by vlad-watcher** [comment]
@mgrybyk I would like to have that option please (trying to run in under Mac OS with same error).
If i can contribute to the code to make that available faster, please let me know

**Comment by shwetankverma** [comment]
@mgrybyk I am also facing the same. I want to use it with Windows runner.. any suggestion? Can I use this -- **mgrybyk/allure-report-branch-action@v1.1.4**

**Comment by mgrybyk** [comment]
@vlad-watcher @shwetankverma the question and solution is the same.
I can built the JavaScript action but the limitation is that you have to install java manually in windows or macos container manually.
Will this work for you?

**Comment by shwetankverma** [comment]
Yes that will work..

**Comment by rahulshrivastava-eaton** [comment]
@mgrybyk yes it will be nice we can install java on self-hosted windows runners .

**Comment by mgrybyk** [comment]
@vlad-watcher @shwetankverma @rahulshrivastava-eaton 

Here you go, the javascript version os the [allure-report-branch-action](https://github.com/mgrybyk/allure-report-branch-action)
- repo https://github.com/mgrybyk/allure-report-branch-js-action
- market https://github.com/marketplace/actions/allure-report-with-history-per-branch-js

I've tested it in default github runners in ubuntu, windows and macos. All of them have java preinstalled. 

Please let me know if that works for you.

Thank you

**Comment by shwetankverma** [comment]
so my allure-reports are generated in the folder allure-raw. These are raw reports which contains xml and videos of the run.
I used this action as -
      ```
- name: Run Tests
        working-directory: e2e
        run: |
          npm run test1
        continue-on-error: true

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages # branch name
          path: gh-pages

      - name: Allure Report Action
        uses: mgrybyk/allure-report-branch-js-action@v1.0.0
        id: allure-report
        with:
          report_id: 'self-test'
          gh_pages: 'gh-pages'
          report_dir: 'allure-raw'

      - name: Git Commit and Push Action
        uses: mgrybyk/git-commit-pull-push-action@v1.2.3
        with:
          repository: gh-pages
          branch: gh-pages
          pull_args: --rebase -X ours
```

but its failing --
{
  report_dir: 'allure-raw',
  gh_pages: 'gh-pages',
  report_id: 'self-test',
  runUniqueId: '773254304[8](https://github.com/org/repo/actions/runs/7732543048/job/21082688996#step:7:9)_[17](https://github.com/org/repo/actions/runs/7732543048/job/21082688996#step:7:18)06737285362',
  ref: 'refs/heads/sv-selfhosted',
  repo: { owner: 'org', repo: 'repo' },
  branchName: 'sv-selfhosted',
  reportBaseDir: 'gh-pages\\allure-js-action\\sv-selfhosted\\self-test',
  reportDir: 'gh-pages\\allure-js-action\\sv-selfhosted\\self-test\\7732543048_1706737285362',
  report_url: 'https://org.github.io/repo/allure-js-action/sv-selfhosted/self-test/7732543048_1706737285362',
  listDirs: false
}
allure-results folder has no json files: allure-raw
Error: There were issues with the allure-results, see error above.

**Comment by mgrybyk** [comment]
Which means the path to report is incorrect or the folder is empty.

I may suggest to add some command to list files in the report dir (I guess it's dir allure-raw).

@shwetankverma can you try debugging it a bit more?

**Comment by shwetankverma** [comment]
Actually path is correct, and it has list of dir and folders.
I also confirmed `allure-raw` folder exists. The  list files gives the output as:


        Directory: C:\actions-runner\_work\abc\repo\allure-raw
    
    
    Mode                LastWriteTime         Length Name                                                                  
    ----                -------------         ------ ----                                                                  
    d-----        1/31/2024   8:47 PM                videos                                                                
    -a----        1/31/2024   9:00 PM          18255 8a66b2d9-79dd-4887-b5a9-9cb6c6843e68-testsuite.xml

**Comment by mgrybyk** [comment]
@shwetankverma I don't know what is that xml. Did you pay attention to the log message? 
`allure-results folder has no json files: allure-raw`.

I have some questions and want to ask you to help me with something:
- How did you generate the xml file? 
- Which version of allure do you use? 
- can you please attach the XML file?

My assumption is that the allure plugin generates json files (not XML). I might be wrong though.

**Comment by baev** [comment]
> My assumption is that the allure plugin generates json files (not XML). I might be wrong though.

Allure supports many different formats, including JUnit XML, Allure 1 XML, Allure 2 JSON, TRX, XUnit XML, etc.

`-testsuite.xml ` is the file generated by old adaptors (from Allure 1). I would like to know why you still use it; I believe we have already released official versions of Allure 2 integrations for the majority of the test frameworks.

**Comment by shwetankverma** [comment]
so we are usin wdio/allure-reporter. When the test execution completes, allure-raw folder is generated.
see this snippet in our wdio.shared.conf.ts --

```
reporters: [
    [
      video,
      {
        saveAllVideos: false,
        videoSlowdownMultiplier: 3,
        outputDir: './allure-raw/videos',
        videoFormat: 'mp4',
      },
    ],
    "spec",
    [
      "allure",
      {
        outputDir: "./allure-raw",
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: true,
      },
    ],
  ],
```
allure-raw directory consists of videos and xml (which I shared previously)
now to generate a proper report, locally we can run as allure generate allure-raw <dest-folder> and deploy on gh-pages. this allure-report has directory structure as in attached image.
![allure-gh pages](https://github.com/simple-elf/allure-report-action/assets/11815328/43d9684b-05f1-44c8-b487-87e2a2806079)


while using default gh-runner as ubuntu, i can do these as --

      ```
- name: Run Tests
        working-directory: e2e
        run: |
          npm run test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-raw
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
```

Hope I am able to explain now.
